# dataset params
data_path_train: C:\Users\chere\PycharmProjects\datas\super_res\train
train_in_dir: low_res
train_out_dir: high_res

data_path_test: C:\Users\chere\PycharmProjects\datas\super_res\val
test_in_dir: low_res
test_out_dir: high_res

image_super_resolution: 256
image_base_resolution: 128


# total model train parameters
epochs: 100
batch_size: 4
workers: 4
accumulation_steps: 5
save_dir: '../runs'
save_run_name: 'run'

# gan model train
pretrain_gen_net: '../runs/best_pretrain/SRresnet16_2upscale.pth'
discr_lr: 0.0002
discr_weight_decay: 0.000001

# optim hyperparameters
opt_algo: "AdamW"
lr: 0.0002
weight_decay: 0.000001
momentum: 0.9

# lr_scheduler
sched_type: 'explr'
lr_step: 5
lr_gamma: 0.75
lr_min: 0.000001
cosine_lr_period: 20

# model hyperparams
upscale_factor: 2
n_blocks: 16
beta: 0.1
num_vgg_layer_mse: 35

# device params
device: 'cuda'
deterministic: False
parallel: False
amp: True




